### ISSUE TITLE
Kendo Theme Material failed

### ISSUE THREAD

**Issue by jcalvezar** [umutesen/AngularProjectStructure#1]
Hello,
When I cloned the repository, after a npm install, running ng serve says:

ERROR in multi ./node_modules/@progress/kendo-theme-material/dist/all.css ./src/styles.css
Module not found: Error: Can't resolve '/home/jca/angularcosas/AngularProjectStructure/node_modules/@progress/kendo-theme-material/dist/all.css' in '/home/jca/angularcosas/AngularProjectStructure'

Then, I manually added it:

npm install --save @progress/kendo-theme-material

And now "ng serve" works perfect

**Comment by umutesen** [comment]
Thanks for pointing it out :+1:
